### ISSUE TITLE
30 дизайнов цветомузыки и более 90 обычных эффектов на esp8266 и mqtt

### ISSUE THREAD

**Issue by anrada73** [AlexGyver/ColorMusic#16]
https://www.youtube.com/watch?v=IG_WMCPlVx4

**Comment by denis86111** [comment]
классная штука, только где скачать прошивку pro?

**Comment by anrada73** [comment]
https://www.youtube.com/watch?v=DUdIw5CBIhU&t   в описании есть демо версия и как со мной связаться
